## PageRank

In [7]:
import numpy as np
import time

d = 0.15
np.set_printoptions(precision=10,suppress=True)
file_name = ['graph_1.txt','graph_2.txt','graph_3.txt','graph_4.txt','graph_5.txt','graph_6.txt','project1_data.txt','project1_data2.txt']
#file_name = ['graph_1.txt','graph_1_newp.txt','graph_2.txt','graph_2_newp.txt','graph_3.txt','graph_3_newp.txt']
for file in file_name:
    start = time.time()
    max_value = 1
    print('file name:', file)
    with open('./hw3dataset/' + file) as f:
        txt_data = f.read().split('\n')
    for item in txt_data:
        if item[:item.find(',')] != '' and item[item.find(',')+1:] != '':
            max_value = max(int(item[:item.find(',')]),int(item[item.find(',')+1:]),max_value)
    original = np.zeros((max_value, max_value))
    for item in txt_data:  
        if item[:item.find(',')] != '' and item[item.find(',')+1:] != '':
            source = int(item[:item.find(',')])
            target = int(item[item.find(',')+1:])
            original[source-1][target-1] = 1
    sum = np.sum(original,axis=1)
    #original matix normalize
    for row in range(original.shape[1]):
        for col in range(original.shape[0]):
            if original[row][col] != 0:
                original[row][col] = original[row][col] / sum[row]
    trans = np.transpose(original)    
    pr = np.zeros((trans.shape[0], 1))
    for i in range(trans.shape[0]):
        pr[i] = float(1) / trans.shape[0]
    c = 0
    total = 1
    while total > 0.01:
        c += 1
        if c > 1:
            total = 0
            tmp = (1 - d) * np.dot(trans, pr_new) + d * pr_new
            #normalize
            norm = np.sum(tmp,axis=0) 
            for i in range(trans.shape[0]):
                if tmp[i] != 0:
                    tmp[i] = tmp[i] / norm[0]
            for sub in range(pr_new.shape[0]):
                total += abs(pr_new[sub][0] - tmp[sub][0])
            pr_new = tmp
        else:
            pr_new = (1 - d) * np.dot(trans, pr) +  d * pr
            #normalize
            norm = np.sum(pr_new,axis=0) 
            for i in range(trans.shape[0]):
                if pr_new[i] != 0:
                    pr_new[i] = pr_new[i] / norm[0]
    print('number of iterations:',c) 
    end = time.time()  
    print('time cost:',end-start,'s')
    print('pagerank:')
    print(pr_new)
    print('-'*80)
    with open('./PageRank_result/' + file, 'a') as fi:
        fi.write(str(pr_new))

file name: graph_1.txt
number of iterations: 18
time cost: 0.00164794921875 s
pagerank:
[[0.0000000176]
 [0.0000018121]
 [0.000088249 ]
 [0.0027005621]
 [0.0582122171]
 [0.9389971421]]
--------------------------------------------------------------------------------
file name: graph_2.txt
number of iterations: 2
time cost: 0.0012111663818359375 s
pagerank:
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
--------------------------------------------------------------------------------
file name: graph_3.txt
number of iterations: 4
time cost: 0.0005412101745605469 s
pagerank:
[[0.1671432617]
 [0.3328567383]
 [0.3328567383]
 [0.1671432617]]
--------------------------------------------------------------------------------
file name: graph_4.txt
number of iterations: 5
time cost: 0.0005612373352050781 s
pagerank:
[[0.3037372883]
 [0.1663863829]
 [0.1406480282]
 [0.1055663378]
 [0.1780847768]
 [0.0446812689]
 [0.0608959171]]
--------------------------------------------------------------------------------
f

number of iterations: 25
time cost: 0.764976978302002 s
pagerank:
[[0.          ]
 [0.0000030118]
 [0.000149805 ]
 ...
 [0.0008752745]
 [0.0004289733]
 [0.0001923897]]
--------------------------------------------------------------------------------
file name: project1_data.txt
number of iterations: 4
time cost: 0.001485586166381836 s
pagerank:
[[0.0376319037]
 [0.0185073415]
 [0.1118535759]
 [0.0990106542]
 [0.1369006687]
 [0.1369006687]
 [0.1217382718]
 [0.1184439522]
 [0.1369006687]
 [0.0821122946]]
--------------------------------------------------------------------------------
file name: project1_data2.txt
number of iterations: 5
time cost: 0.0013298988342285156 s
pagerank:
[[0.0199842285]
 [0.0384177532]
 [0.0867137387]
 [0.0873813945]
 [0.1410421118]
 [0.1122243354]
 [0.1884272962]
 [0.13659223  ]
 [0.1892169118]]
--------------------------------------------------------------------------------
